<?php


namespace app\controller;

use app\controller\Base;

use app\model\GameType;
use app\model\Odds as models;
use app\traits\PublicCrudTrait;
use hg\apidoc\annotation as Apidoc;
class Odds extends Base
{
    protected $model;
    use PublicCrudTrait;

    /**
     * 桌面控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @Apidoc\Title("赔率列表")
     * @Apidoc\Method("POST")
     * @Apidoc\Url("/gameodds/list")
     * @Apidoc\Param("token", type="string",require=true, desc="token")
     * @Apidoc\Param("page", type="int",require=true,default="1", desc="页码")
     * @Apidoc\Param("limit", type="int",require=true,default="10",desc="条数")
     * @Apidoc\Returned("data", type="bool", desc="返回成功失败结果")
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 100);
        //查询搜索条件
        $post = array_filter($this->request->post());
        $map = [];
        isset($post['type_id']) && $map  = ['game_type_id'=>$post['type_id']];

        $list = $this->model->page_list($map, $limit, $page);
         $this->success($list);
    }

    /**
     * @Apidoc\Title("赔率添加")
     * @Apidoc\Method("POST")
     * @Apidoc\Url("/gameodds/add")
     * @Apidoc\Param("token", type="string",require=true, desc="token")
     * @Apidoc\Param("game_type_id", type="int",require=true, desc="游戏类型id")
     * @Apidoc\Param("game_tip_name", type="string",require=true, desc="桌面提示文字")
     * @Apidoc\Param("peilv", type="string",require=true, desc="赔率")
     * @Apidoc\Param("sort", type="int",require=true, desc="排序")
     * @Apidoc\Param("remark", type="string",require=true, desc="备注")
     * @Apidoc\Returned("data", type="bool", desc="返回成功失败结果")
     */
    public function add()
    {
        $post = $this->request->post();
        $save = $this->model->save($post);
        if ($save)  $this->success([]);
         $this->failed('新增失败');
    }


    /**
     * @Apidoc\Title("赔率编辑")
     * @Apidoc\Method("POST")
     * @Apidoc\Url("/gameodds/edit")
     * @Apidoc\Param("token", type="string",require=true, desc="token")
     * @Apidoc\Param("id", type="int",require=true, desc="赔率列表对应的id")
     * @Apidoc\Param("game_type_id", type="int",require=true, desc="游戏类型id")
     * @Apidoc\Param("game_tip_name", type="string",require=true, desc="桌面提示文字")
     * @Apidoc\Param("peilv", type="string",require=true, desc="赔率")
     * @Apidoc\Param("sort", type="int",require=true, desc="排序")
     * @Apidoc\Param("remark", type="string",require=true, desc="备注")
     * @Apidoc\Returned("data", type="bool", desc="返回成功失败结果")
     */
    public function edit()
    {
        $post = $this->request->post();
        if (!isset($post['id']) || $post['id'] <=0)  $this->failed('修改失败');
        //执行修改数据
        $save = $this->model->update($post);
        if ($save)  $this->success([]);
         $this->failed('修改失败');
    }
}